before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
brews:
  - tap:
      owner: mbode
      name: homebrew-tap
    homepage: "https://github.com/mbode/terraform-state-mover"
    description: "Refactoring Terraform code has never been easier"
    folder: Formula
    test: |
      system "#{bin}/terraform-state-mover", "--version"
