name: Check
on: [push, pull_request]
jobs:


  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Install terraform
        run: wget https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip -O /tmp/terraform.zip && sudo unzip -o -d /usr/local/bin/ /tmp/terraform.zip

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.33

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v -cover -coverprofile=coverage.txt ./...

      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

  pre012:
    name: pre012
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Install terraform
        run: wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip -O /tmp/terraform.zip && sudo unzip -o -d /usr/local/bin/ /tmp/terraform.zip

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v -cover -coverprofile=coverage.txt ./...

      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

  terraform_version_compatibility:
    name: Terraform compatibility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform:
          - 0.10.1
          - 0.10.2
          - 0.10.3
          - 0.10.4
          - 0.10.5
          - 0.10.6
          - 0.10.7
          - 0.10.8
          - 0.11.0
          - 0.11.1
          - 0.11.2
          - 0.11.3
          - 0.11.4
          - 0.11.5
          - 0.11.6
          - 0.11.7
          - 0.11.8
          - 0.11.9
          - 0.11.10
          - 0.11.11
          - 0.11.12
          - 0.11.13
          - 0.11.14
          - 0.12.0
          - 0.12.1
          - 0.12.2
          - 0.12.3
          - 0.12.4
          - 0.12.5
          - 0.12.6
          - 0.12.7
          - 0.12.8
          - 0.12.9
          - 0.12.10
          - 0.12.11
          - 0.12.12
          - 0.12.13
          - 0.12.14
          - 0.12.15
          - 0.12.16
          - 0.12.17
          - 0.12.18
          - 0.12.19
          - 0.12.10
          - 0.12.21
          - 0.12.22
          - 0.12.23
          - 0.12.24
          - 0.12.25
          - 0.12.26
          - 0.12.27
          - 0.12.28
          - 0.12.29
          - 0.13.0
          - 0.13.1
          - 0.13.2
          - 0.13.3
          - 0.13.4
          - 0.13.5
          - 0.14.0
          - 0.14.1
          - 0.14.2
          - 0.14.3

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Install terraform
        run: wget https://releases.hashicorp.com/terraform/${{ matrix.terraform }}/terraform_${{ matrix.terraform }}_linux_amd64.zip -O /tmp/terraform.zip && sudo unzip -o -d /usr/local/bin/ /tmp/terraform.zip

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v .